name: Use Reusable C++ Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-test:
    uses: ./.github/workflows/buildtestccpp.yml
    with:
      compiler: clang
      build-system: make
