name: Use Reusable C++ Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-and-test:
    uses: ./.github/workflows/secscan.yml
    with:
      compiler: clang
      build-system: make
